const express = require("express");
const error = require("../middleware/error");
const auth = require("../routes/auth");
const users = require("../routes/users");
const uploadImages = require("../routes/uploadImages");
const categoryRoute = require("../routes/categoryRoute");
const WebCategoryRoute = require("../routes/WebCategoryRoute");
const WebSubCategoryRoute = require("../routes/WebSubCategoryRoute");
const ServicesCategoryRoute = require("../routes/ServicesCategoryRoute");
const ServicesSubCategoryRoute = require("../routes/ServicesSubCategoryRoute");
const messageRoutes = require("../routes/messageRoutes");
const notificationRoute = require("../routes/notificationRoute");
const authMiddleware = require("../middleware/auth");
const supportRoute = require("../routes/supportRoute");
const orderRoutes = require("../routes/orderRoutes");
const ratingRoutes = require("../routes/ratingRoutes");
const couponRoute = require("../routes/couponRoute");
const BannerRoute = require("../routes/BannerRoute");
const ShopOrder = require("../routes/ShopOrder");
const invoiceRoute = require("../routes/invoiceRoute");
const newInvoiceRoute = require("../routes/newInvoiceRoute");
const assignDriverRoutes = require("../routes/assignDriverRoutes");
// Routes main file
module.exports = function (app) {
  app.use(express.json());
  app.use("/api/auth", auth);
  app.use("/api/users", users);
  app.use("/api/image", uploadImages);
  app.use("/api/category", categoryRoute);
  app.use("/api/webcat", WebCategoryRoute);
  app.use("/api/websubcat", WebSubCategoryRoute);
  app.use("/api/servicecat", ServicesCategoryRoute);
  app.use("/api/servicesubcat", ServicesSubCategoryRoute);
  app.use("/api/order", authMiddleware, orderRoutes);
  app.use("/api/coupon", couponRoute);
  app.use("/api/rating", ratingRoutes);
  app.use("/api/msg", authMiddleware, messageRoutes);
  app.use("/api/notification", authMiddleware, notificationRoute);
  app.use("/api/support", supportRoute);
  app.use("/api/banner", BannerRoute);
  app.use("/api/shop-order", ShopOrder);
  app.use("/api/payment", invoiceRoute);
  app.use("/api/payment-new", newInvoiceRoute);
  app.use("/api/assign-driver", assignDriverRoutes);
  app.use(error);
};
